name: Compile Java Code

on:
  push:
    branches: ['**']  # Trigger on push to any branch
  workflow_dispatch:  # Allow manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [17, 21]  # Test with both Java versions
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Compile main Java code
        run: ./gradlew compileJava --no-daemon --console=plain
        
      - name: Compile test Java code  
        run: ./gradlew compileTestJava --no-daemon --console=plain
        
      - name: Assemble JAR files
        run: ./gradlew assemble --no-daemon --console=plain